### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by lvthillo** [JPStrydom/Crypto-Trading-Bot#16]
I Pulled the latest code of yesterday but after a while it crashes and I need to restart the app (and it works again for some time):

```
2018/05/01 09:28:32 AM - ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/xxx/Documents/Crypto-Trading-Bot/src/app.py", line 94, in <module>
    Trader.analyse_pauses()
  File "/Users/xxx/Documents/Crypto-Trading-Bot/src/trader.py", line 48, in analyse_pauses
    current_balance = self.Messenger.send_balance_slack(self.get_non_zero_balances(),
  File "/Users/xxx/Documents/Crypto-Trading-Bot/src/trader.py", line 406, in get_non_zero_balances
    balances_data = self.Bittrex.get_balances()
  File "/Users/xxx/Documents/Crypto-Trading-Bot/src/bittrex.py", line 320, in get_balances
    return self.api_query("getbalances", {})
  File "/Users/xxx/Documents/Crypto-Trading-Bot/src/bittrex.py", line 129, in api_query
    return self.dispatch(request_url, apisign)
  File "/Users/xxx/Documents/Crypto-Trading-Bot/src/bittrex.py", line 67, in using_requests
    headers={"apisign": apisign}
  File "/Users/xxx/venv/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


```

I've also disabled my slackbot.

**Comment by JPStrydom** [comment]
That seems like a Bittrex error. How often does this occur?

**Comment by lvthillo** [comment]
@JPStrydom I was afraid so. Well, not that much, had it twice till now. Once yesterday, once today. (I'm using/testing your bot only since a few days so it's not that reliable)

**Comment by JPStrydom** [comment]
You can delete the "balance" key from your "pauseParameters" inside the "settings.json" file. This will stop the bot from checking for balances for the slack update (which you're not using anyway).
The balance functionality is quite new and has been giving some issues.

**Comment by lvthillo** [comment]
@JPStrydom okay thanks
