### ISSUE TITLE
program stop?

### ISSUE THREAD

**Issue by fachos** [JPStrydom/Crypto-Trading-Bot#21]
Resuming tracking on all 197 markets.
No Sell on BTC-FCT   	->		RSI: 43		Profit Margin: 0.86%		Sell Price: 0.00207551		URL: https://bittrex.com/Market/Index?MarketName=BTC-FCT
Resuming tracking on all 197 markets.
Sell on BTC-FCT   	->		RSI: 43		Profit Margin: 2.05%		Sell Price: 0.00210000		URL: https://bittrex.com/Market/Index?MarketName=BTC-FCT

An unknown exception occurred. Exiting program.
See the latest log file for more information.

the log says : 

2018/06/03 02:20:17 PM - ERROR: <class 'Exception'>
Traceback (most recent call last):
  File "app.py", line 96, in <module>
    Trader.analyse_sells()
  File "/Users/nameless/botz/Crypto-Trading-Bot/src/trader.py", line 68, in analyse_sells
    self.sell_strategy(coin_pair)
  File "/Users/nameless/botz/Crypto-Trading-Bot/src/trader.py", line 121, in sell_strategy
    self.sell(coin_pair, current_sell_price, sell_stats)
  File "/Users/nameless/botz/Crypto-Trading-Bot/src/trader.py", line 227, in sell
    self.Messenger.send_sell_gmail(sell_order_data["result"], stats)
  File "/Users/nameless/botz/Crypto-Trading-Bot/src/messenger.py", line 203, in send_sell_gmail
    self.send_email(subject, message)
  File "/Users/nameless/botz/Crypto-Trading-Bot/src/messenger.py", line 134, in send_email
    server.login(self.login, self.password)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 730, in login
    raise last_exception
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbs_\n5.7.14 4HTmswob-IAJ2LK6l-yT2LBRKNwxLu1E_KLi-GS3dsP2YNNlPwrcR5Fi9UNAskCyh37gIBxNy1\n5.7.14 DsHrtQSbBYMuY4hRhWOCda1ECsdfsf6_H0JFJnsSzdQV3JS0JXSDADKUAai8yTUdsZjmfqkIh-MJ9xw8HE\n5.7.14 \n5.7.14 3vBXKDkONhMJM2RQwLkUZvPBEjdus> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 r26-v6sm43896861pfj.180 - gsmtp')

**Comment by JPStrydom** [comment]
Mhhh that seems like an authentication error on the Bittrex API. Have you been able to log in and trade manually on the Bittrex platform?

**Comment by fachos** [comment]
hi... yes can manually trade via web base.... i fix the problem... but i had another problem here... can i choose pairs only few altcoin? maybe 10-20 only rather than 190++ coin there... thank you

**Comment by JPStrydom** [comment]
I've had a few people ask me to "whitelist" certain coins only. I'll look into it if I get some time 👍

**Comment by fachos** [comment]
hi can u add telegrambot together with ur new release? 
also im waiting the whitelist pair coin.. thank you
