### ISSUE TITLE
unable to run the bot

### ISSUE THREAD

**Issue by akkighanate** [JPStrydom/Crypto-Trading-Bot#22]
Hi i have done the setup in windows and i am getting below error can you help me out here

**BOT logs**
2018/08/30 10:29:43 PM - ERROR: 'buy'
Traceback (most recent call last):
  File "app.py", line 94, in <module>
    `Trader.analyse_pauses()`
  File "C:\Users\Akki\Desktop\New folder\Crypto-Trading-Bot-master\Crypto-Trading-Bot-master\src\trader.py", line 40, in analyse_pauses
    if self.Database.check_resume(self.pause_params["buy"]["pauseTime"], "buy"):
KeyError: 'buy'

**Comment by JPStrydom** [comment]
What does your log file look like?

**Comment by akkighanate** [comment]
@jpstrydom above mention details are from logs file

Even i tried to change the pvt keys still getting same error

**Comment by Naveen-Zerocool** [comment]
@akkighanate The problem was in settings.json file 'pause_params' will be empty. Replace below lines :

    "pauseParameters": { }

with :

    "pauseParameters": {
            "buy": {
                "rsiThreshold": 0,
                "pauseTime": 0
            },
            "sell": {
                "profitMarginThreshold": 0,
                "pauseTime": 0
            },
            "balance": {
                "pauseTime": 0
            }
        }

. Now it should work.

**Comment by akkighanate** [comment]
> @akkighanate The problem was in settings.json file 'pause_params' will be empty. Replace below lines :
> 
> ```
> "pauseParameters": { }
> ```
> with :
> 
> ```
> "pauseParameters": {
>         "buy": {
>             "rsiThreshold": 0,
>             "pauseTime": 0
>         },
>         "sell": {
>             "profitMarginThreshold": 0,
>             "pauseTime": 0
>         },
>         "balance": {
>             "pauseTime": 0
>         }
>     }
> ```
> . Now it should work.

Hello Brother @Naveen-Zerocool .
i tried to change but i got some other error...can you pls ping me in whatsapp +91  / Skype live:akshayghanate need your help in resolving the issue
