### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by tr4nscr1pt** [JPStrydom/Crypto-Trading-Bot#9]
python app.py
Traceback (most recent call last):
  File "app.py", line 81, in <module>
    secrets = get_secrets()
  File "app.py", line 33, in get_secrets
    secrets_content = get_json_from_file(secrets_file_directory, secrets_template)
  File "/home/node/Crypto-Trading-Bot/src/directory_utilities.py", line 38, in get_json_from_file
    except (IOError, json.decoder.JSONDecodeError):
AttributeError: 'module' object has no attribute 'JSONDecodeError'

**Comment by tr4nscr1pt** [comment]
Solved by running **python3.6 app.py**
